### PR TITLE
Removed DShield links

### PR DESCRIPTION
**Pull request by AndrewDaws**
Fixed issue #110

### CODE REVIEW

**Comment by XhmikosR** [comment]
The High list should be recommended and not crossed out IMHO @WaLLy3K

**Comment by AndrewDaws** [comment]
> EDIT2: The lists shouldn't be crossed out, though, they should be removed.

As I mentioned in issue #110, the post stated they may try to find new input feeds. As to how soon, or how much effort they are putting into actually finding new feeds? I have no idea. But I figured in the short term it might be worth just crossing off for now since they specifically stated they are only suspending the lists, not deprecating them. So I don't know if it's worth removing the lists entirely when they were a very legitimate and good source at one point.

I tried looking for any sort of standard practice for this repo for dealing with this sort of issue, but didn't find any practice that was always followed. In some cases lists were kept, but marked off, to warn people not to use that list that is also found recommended/used elsewhere, meanwhile others were outright removed. So this is definitely a decision for @WaLLy3K for what is the correct course of action.

**Comment by XhmikosR** [comment]
Yeah, but now they are serving empty content. They should be removed, and if they come back someone should add them again.

**Comment by WaLLy3K** [comment]
I came into this with the mindset that they should be crossed out (as in "Yes, I acknowledge that I'm aware of these lists but don't recommend them") but since they're suspended and *not* serving any content, I agree with discussion in this PR and I reckon it's fair to remove them pending those lists serving content again.

**Pull request merged**
