### PR TITLE
Tweak HTML files

### PR DESCRIPTION
**Pull request by XhmikosR**
* remove unneeded HTML end tags
* fix `meta viewport`
* fix missing closing `a` tag
* streamline trailing slashes

### CODE REVIEW

**Comment by XhmikosR** [comment]
@WaLLy3K not sure if you need to backport these to your PHP files, but if so just don't forget to do it 🙂

**Comment by WaLLy3K** [comment]
Looks good to me! It shouldn't affect any of my other things, but we'll see how we go 😅

**Comment by XhmikosR** [comment]
It will beO OK, and if not we are around to fix any issues :) That being said, see if you need to backport any list URL updates to your PHP files too.

**Comment by XhmikosR** [comment]
BTW currently there's only one broken link, which started to happen after I made this patch: https://blocklist.kowabit.de/list.txt returns an SSL error but I guess we need to wait.

**Comment by WaLLy3K** [comment]
> BTW currently there's only one broken link, which started to happen after I made this patch: https://blocklist.kowabit.de/list.txt returns an SSL error but I guess we need to wait.

Looks like the certificate was renewed manually February last year, and hasn't been auto-updated for 2020. [Updated the list](https://github.com/WaLLy3K/wally3k.github.io/commit/ab880266ae17dc72acc8f35971518aa9854207e1), so thanks!

> That being said, see if you need to backport any list URL updates to your PHP files too.

My `lists.php` file scrapes the text before the closing `</a>` tag on the source of `firebog.net`, so that'll be sorted automatically :)

**Pull request merged**
